version: 0.0
os: linux
files:
  - source: source
    destination: /webapps/portfolio
hooks:
  AfterInstall:
    - location: scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/RunApplication.sh
      timeout: 3600
